//------------------------------------------------------------------------------
// <auto-generated>
// 	This code was auto-generated by Crockhead.Table
// 	version 0.0.1
// 	update 2025-09-23 19:36:26
// </auto-generated>
//------------------------------------------------------------------------------
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Crockhead.Table;


/// <summary>
/// ExampleTable Recordable Data.
/// </summary>
[JsonObject(MemberSerialization.OptIn)]
public class ExampleTableRecord : IRecordable
{
	/// <summary>
	/// Id.
	/// </summary>
	[JsonProperty]
	public int Id { set; get; }

	/// <summary>
	/// StringValue.
	/// </summary>
	[JsonProperty]
	public string StringValue { set; get; }

	/// <summary>
	/// FloatValue.
	/// </summary>
	[JsonProperty]
	public float FloatValue { set; get; }

	/// <summary>
	/// IntDictionaryValue.
	/// </summary>
	[JsonProperty]
	public IntDictionary IntDictionaryValue { set; get; }

	/// <summary>
	/// StringListValue.
	/// </summary>
	[JsonProperty]
	public StringList StringListValue { set; get; }

	/// <summary>
	/// IntListValue.
	/// </summary>
	[JsonProperty]
	public IntList IntListValue { set; get; }

	/// <summary>
	/// EmptyIntDictionaryValue.
	/// </summary>
	[JsonProperty]
	public IntDictionary EmptyIntDictionaryValue { set; get; }

	/// <summary>
	/// EmptyIntListValue.
	/// </summary>
	[JsonProperty]
	public IntList EmptyIntListValue { set; get; }

	/// <summary>
	/// BoolValue.
	/// </summary>
	[JsonProperty]
	public bool BoolValue { set; get; }

	/// <summary>
	/// 필드 갯수.
	/// </summary>
	int IRecordable.GetFieldCount()
	{
		return 9;
	}

	/// <summary>
	/// 필드 이름.
	/// </summary>
	string IRecordable.GetFieldName(int index)
	{
		switch (index)
		{
			case 0: return "Id";
			case 1: return "StringValue";
			case 2: return "FloatValue";
			case 3: return "IntDictionaryValue";
			case 4: return "StringListValue";
			case 5: return "IntListValue";
			case 6: return "EmptyIntDictionaryValue";
			case 7: return "EmptyIntListValue";
			case 8: return "BoolValue";
			default: return string.Empty;
		}
	}

	/// <summary>
	/// 필드 타입.
	/// </summary>
	Type IRecordable.GetFieldType(int index)
	{
		switch (index)
		{
			case 0: return Id.GetType();
			case 1: return StringValue.GetType();
			case 2: return FloatValue.GetType();
			case 3: return IntDictionaryValue.GetType();
			case 4: return StringListValue.GetType();
			case 5: return IntListValue.GetType();
			case 6: return EmptyIntDictionaryValue.GetType();
			case 7: return EmptyIntListValue.GetType();
			case 8: return BoolValue.GetType();
			default: return null;
		}
	}

	/// <summary>
	/// 필드 값.
	/// </summary>
	object IRecordable.GetFieldValue(int index)
	{
		switch (index)
		{
			case 0: return Id;
			case 1: return StringValue;
			case 2: return FloatValue;
			case 3: return IntDictionaryValue;
			case 4: return StringListValue;
			case 5: return IntListValue;
			case 6: return EmptyIntDictionaryValue;
			case 7: return EmptyIntListValue;
			case 8: return BoolValue;
			default: return null;
		}
	}
}