<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.0.1</Version>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>disable</Nullable>
		<ProduceReferenceAssembly>True</ProduceReferenceAssembly>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageId>Crockhead.Table</PackageId>
		<Product>$(PackageId)</Product>
		<Title>$(PackageId)</Title>
		<AssemblyName>$(PackageId)</AssemblyName>
		<Company>Crockhead Studio</Company>
		<Authors>ddukbaek2</Authors>
		<Description>Generates C# and JSON files from Custom-Rule-Based XLSX Tables and Provides Functionality to Load These Tables.</Description>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/ddukbaek2/Crockhead.Table.git</RepositoryUrl>
		<!-- <PackageLicenseExpression>MIT</PackageLicenseExpression> -->
		<!-- <LicenseExpression>$(PackageLicenseExpression)</LicenseExpression> -->
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageTags>core;utility;base;table</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/ddukbaek2/Crockhead.Table</PackageProjectUrl>
		<ProjectUrl>$(PackageProjectUrl)</ProjectUrl>
		<PackageDirectory>$(MSBuildProjectDirectory)\bin\$(Configuration)\</PackageDirectory>
		<DeployOnBuild>True</DeployOnBuild>
		<DistOnPack>False</DistOnPack>
		<OutputDir>$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)\</OutputDir>
		<LibraryFilePath>$(OutputDir)$(AssemblyName).dll</LibraryFilePath>
		<DocumentFilePath>$(OutputDir)$(AssemblyName).xml</DocumentFilePath>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="LICENSE" Pack="true" PackagePath="\" />
		<PackageReference Include="Crockhead.Core" Version="0.0.13" />
		<PackageReference Include="ExcelDataReader" Version="3.8.0" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<Target Name="RemoveAllPackages" BeforeTargets="Build;Pack">
		<ItemGroup>
			<PackageFilePattern Include="$(PackageDirectory)*.nupkg" />
			<SymbolPackageFilePattern Include="$(PackageDirectory)*.snupkg" />
		</ItemGroup>
		<Delete Files="@(PackageFilePattern);@(SymbolPackageFilePattern)" />
	</Target>

	<Target Name="Deployment" AfterTargets="Build" Condition="'$(Configuration)'=='Release' and '$(DeployOnBuild)'=='True'">
		<Exec Command="deployment.bat $(DocumentFilePath) $(LibraryFilePath)" WorkingDirectory="$(ProjectDir)" />
	</Target>
	<Target Name="Distribution" AfterTargets="Pack" Condition="'$(Configuration)'=='Release' and '$(DistOnPack)'=='True'">
		<Exec Command="distribution.bat" WorkingDirectory="$(ProjectDir)" />
	</Target>

</Project>
